version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - VITE_APP_API_URL=http://localhost:8000/api/v1/
      - VITE_APP_TURNSTILE_SITEKEY=0x4AAAAAABD6_xW0TcNKIpLl
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DATABASE_URL=mysql://gen_user:qcs3pk33@5.129.198.116:3306/default_db
      - TURNSTILE_SITE_KEY=0x4AAAAAABD6_xW0TcNKIpLl
      - TURNSTILE_SECRET_KEY=0x4AAAAAABD6_4MwCRDtOCH3yr4pj-Muyao
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
      - CORS_ALLOW_CREDENTIALS=True

networks:
  app-network:
    driver: bridge
