version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_APP_API_URL=http://127.0.0.1:8000/api/v1/
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=*
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
