version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_APP_API_URL=http://127.0.0.1:8000/api/v1/
      - VITE_APP_ROBLOX_INJECTOR=true
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=*
      - ROBLOX_INJECTOR_MODE=true
      - CORS_ALLOWED_ORIGINS=https://projectcube.tech,http://localhost:80
      - CORS_ALLOWED_METHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization
      - CORS_ALLOW_CREDENTIALS=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
