version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    environment:
      - VITE_APP_API_URL=http://nginx/api/v1/
      - VITE_APP_TURNSTILE_SITEKEY=0x4AAAAAABD6_xW0TcNKIpLl
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=projectcube.tech,localhost,127.0.0.1,backend,nginx
      - DATABASE_URL=mysql://gen_user:qcs3pk33@5.129.198.116:3306/default_db
      - TURNSTILE_SITE_KEY=0x4AAAAAABD6_xW0TcNKIpLl
      - TURNSTILE_SECRET_KEY=0x4AAAAAABD6_4MwCRDtOCH3yr4pj-Muyao
      - CORS_ALLOWED_ORIGINS=https://projectcube.tech,http://localhost:5173
      - CORS_ALLOW_CREDENTIALS=True
    networks:
      - app-network
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
