version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - VITE_APP_API_URL=https://projectcube.tech/api/v1/
      - VITE_APP_TURNSTILE_SITEKEY=0x4AAAAAABD6_xW0TcNKIpLl
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=projectcube.tech,localhost,127.0.0.1,backend
      - DATABASE_URL=mysql://gen_user:qcs3pk33@5.129.198.116:3306/default_db
      - TURNSTILE_SITE_KEY=0x4AAAAAABD6_xW0TcNKIpLl
      - TURNSTILE_SECRET_KEY=0x4AAAAAABD6_4MwCRDtOCH3yr4pj-Muyao
      - CORS_ALLOWED_ORIGINS=https://projectcube.tech,http://localhost:5173
      - CORS_ALLOW_CREDENTIALS=True
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge
